name: ShareUpTime CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    - name: Backend TypeScript Build
      run: |
        cd backend
        npm run build
    
    - name: Backend Tests
      run: |
        cd backend
        npm test
      env:
        NODE_ENV: test

  mobile-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: mobile-app/package-lock.json
    
    - name: Install Mobile Dependencies
      run: |
        cd mobile-app
        npm ci
    
    - name: Mobile TypeScript Check
      run: |
        cd mobile-app
        npx tsc --noEmit
    
    - name: Mobile Tests
      run: |
        cd mobile-app
        npm test
      env:
        NODE_ENV: test

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Security Audit - Backend
      run: |
        cd backend
        npm audit --audit-level=high
    
    - name: Run Security Audit - Mobile
      run: |
        cd mobile-app
        npm audit --audit-level=high

  deploy:
    needs: [backend-test, mobile-test, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy Backend
      run: |
        echo "Backend deployment would happen here"
        # Add your deployment script here
    
    - name: Deploy Mobile App
      run: |
        echo "Mobile app deployment would happen here"
        # Add your app store deployment here